#!/bin/bash

echo "Welcome to imageboard web/image scrapping script"
echo "Is it wallpaper/general (wg) or anime wallpaper (w)?"
read option
echo "Enter folder name:"
read dir
echo "Enter thread no.: (#######)"
read thread
if [[ $option = w ]] ; then
 	mkdir -p /home/saumit/Pictures/Wallpaper/4chget/w/$dir
else
	mkdir -p /home/saumit/Pictures/Wallpaper/4chget/wg/$dir
fi

case "$option" in
	"wg")
		wget -P Pictures/Wallpaper/4chget/wg/$dir -nd -r -l 1 -H -D i.4cdn.org,is2.4chan.org -A png,jpg,jpeg -R '?????????????s.*' https://boards.4chan.org/wg/thread/$thread ;;

	"w")
		wget -P Pictures/Wallpaper/4chget/w/$dir -nd -r -l 1 -H -D i.4cdn.org,is2.4chan.org -A png,jpg,jpeg -R '?????????????s.*' https://boards.4channel.org/w/thread/$thread ;;
esac

