#!/bin/bash

rootpapesdir="$HOME/pix/Wallpaper/4chget"
[ -d "$rootpapesdir" ] || mkdir "$rootpapesdir"
echo "Welcome to 4chan web/image scrapping script"
echo "Is it wallpaper/general (wg) or anime wallpaper (w)?"
read option
echo "Enter folder name:"
read dir
echo "Enter thread no.: (#######)"
read thread
if [[ "$option" = w ]] ; then
 	mkdir -p "$rootpapesdir"/w/"$dir"
	$nel=nel
else
	mkdir -p "$rootpapesdir"/wg/"$dir"
fi

wget -P "$rootpapesdir"/"$option"/"$dir" -nd -r -l 1 -H -D i.4cdn.org,is2.4chan.org -A png,jpg,jpeg -R '????????????????s.*' https://boards.4chan"$nel".org/$option/thread/"$thread"
