#!/bin/sh

##Simple shellscript to set CapsLock key to Escape key automatically
##whenever I plug in any of my keyboard (wired or wireless)

#PreRequisite lsusb/usbutils
[ -z "command -v lsusb" ] && echo "Install usbutils" && exit

[[ 'lsusb | grep -e 04f3:152e -e 25a7:fa67' ]] && setxkbmap -option caps:escape

