#!/bin/sh

latestss=$(ls -t $HOME/pix/Screenshots/ | head -n10 | dmenu -l 10)

[ -z $latestss ] && echo "Nothing selected...quitting" && exit \
||  xclip -selection clipboard -t image/png -i $HOME/pix/Screenshots/$latestss
