require("justsaumit.options")
require("justsaumit.keymaps")
require("justsaumit.plugins")
require("justsaumit.colorscheme")
require("justsaumit.treesitter-config")
require("justsaumit.lualine-config")
require("justsaumit.bufferline-config")
require("justsaumit.lastplace-config")
print ("while(!(success = try());")
